os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.1

env:
  global:
    - FRAMEWORK_NAME="QuerySerialization"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated carthage || brew upgrade carthage; fi

script:
  - eval "$(curl -sL https://swift.vapor.sh/ci)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
