language: generic

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: LOCAL_SWIFT_BRANCH="swift-4.0-release" LOCAL_SWIFT_VERSION="swift-4.0-RELEASE" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="iOS" TEST="simulator" TEST_DEVICE="iPhone-6s" TEST_RUNTIME="iOS-9-3" SCHEME="QuerySerialization-iOS" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="iOS" TEST="simulator" TEST_DEVICE="iPhone-6s" TEST_RUNTIME="iOS-10-3" SCHEME="QuerySerialization-iOS" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="iOS" TEST="simulator" TEST_DEVICE="iPhone-6s" TEST_RUNTIME="iOS-11-0" SCHEME="QuerySerialization-iOS" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="tvOS" TEST="simulator" TEST_DEVICE="Apple-TV-1080p" TEST_RUNTIME="tvOS-11-0" SCHEME="QuerySerialization-tvOS" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="watchOS" TEST="none" SCHEME="QuerySerialization-watchOS" DEPLOY="false"
        - os: osx
          osx_image: xcode9
          language: objective-c
          env: PLATFORM="macOS" TEST="device" DESTINATION="arch=x86_64" SCHEME="QuerySerialization-macOS" DEPLOY="true" FRAMEWORK_NAME="QuerySerialization"

install:
  - sudo bash ./.ci/install.sh

script:
  - set -o pipefail && bash ./.ci/test.sh

before_deploy:
  - bash ./.ci/before_deploy.sh
  